# https://github.com/DataDog/slapr

name: Slack emoji PR updates
on:
  pull_request_review:
    types: [submitted]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/hackadog-slapr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
