# https://github.com/DataDog/hackadog-slapr

name: Slack emoji PR updates
on:
  pull_request_review:
    types: [submitted]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/hackadog-slapr@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPO: DataDog/hackadog-slapr
        SLACK_CHANNEL_ID: CTMRQMGVB
        SLACK_API_TOKEN: "${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}"
