# https://github.com/DataDog/slapr

name: Slack emoji PR updates
on:
  pull_request_review:
    types: [submitted]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
    - uses: DataDog/hackadog-slapr@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
